imports:
  - php

filter:
  paths: [src/*]

tools:
  php_cs_fixer:
    config: { level: psr1 }
  php_hhvm: true
  php_mess_detector: true
  sensiolabs_security_checker: true
  external_code_coverage:
    timeout: '3600'
